# .github/workflows/build.yml
name: Build FFmpeg Android Libraries

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Android NDK r27+
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27b

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Configure & build with CMake
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_PLATFORM=android-21 \
            -DANDROID_ABI="arm64-v8a;armeabi-v7a" \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build . -- -j$(nproc) VERBOSE=1

      - name: Verify 16 KB page alignment
        run: |
          echo "Verifying ELF p_align for 16 KB support…"
          failed=false
          for so in build/output/*/*.so; do
            echo "→ $so"
            readelf -l "$so" | grep LOAD | sed 's/^/   /'
            bad=$(readelf -l "$so" \
              | awk '/^ *LOAD/ {hdr=$0; getline; if ($NF!="0x4000") print hdr "\n" $0}')
            if [ -n "$bad" ]; then
              echo "::error ::Misaligned segments in $so:"
              echo "$bad" | sed 's/^/    /'
              failed=true
            else
              echo "  ✅ OK"
            fi
          done
          $([[ $failed = true ]] && exit 1 || exit 0)

      - name: Upload .so artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-libs
          path: build/output/**/*.so
